### ISSUE TITLE
关于使用许可的咨询

### ISSUE THREAD

**Issue by yanglb** [uu-code007/PixelFreeEffects#21]
您好！

此项目使用许可虽为`MIT`，但初始化时需要提供`授权文件`。

请问项目中的 `pixelfreeAuth.lic` 能否用在我自己的项目中？若不可用我如何获取授权文件？

**Comment by uu-code007** [comment]
> 您好！
> 
> 此项目使用许可仍为`MIT`，但初始化时需要提供`授权文件`。
> 
> 请问项目中的`pixelfreeAuth.lic`可能性用在我自己的项目中吗？如果不可用我如何获取授权文件？

SDK 内核部分付费授权后才可以使用哈

**Comment by wenhaofan** [comment]
作者有联系方式吗
